### ISSUE TITLE
Edit Funktion

### ISSUE THREAD

**Issue by FischLord** [ZIT-P22/IP-Atlas#3]
- Wenn auf edit gedrückt wird sollen alle einzelne Felder änderbar sein
- die Änderung muss validiert werden
- der edit Knopf wird dann durchgängig grün, um die Änderung zu übernehmen
- der edit knopf soll beim hovern im normalen modus grün sein (transition das es langsam grün wird)

- zum Backend will ich gerne eine log datei haben die gefüttert wird

**Comment by FischLord** [comment]
- reasign button raus

**Comment by LeonKohli** [comment]
finish nur kein log
